name: Python CI with uv

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.13"]
    steps:
      - uses: actions/checkout@v4
      - name: Install the latest version of uv and set the python version
        uses: astral-sh/setup-uv@v6
        with:
          python-version: ${{ matrix.python-version }}
      - name: Lint with ruff
        run: uv run --frozen ruff check .
      - name: Check types with mypy
        run: uv run --frozen mypy .
      - name: Test with python ${{ matrix.python-version }}
        run: uv run --frozen pytest
